### ISSUE TITLE
Add support for Ctrl+arrow

### ISSUE THREAD

**Issue by hakash** [hakash/termit#11]
Add Ctrl+arrow support, aliasing HOME, END, PAGE_UP and PAGE_DOWN

**Comment by Reza9472** [comment]
I can work on this issue

**Comment by hakash** [comment]
@Reza9472 Another user has submitted a PR on this issue today. You do however have first go, so if you can submit your PR as soon as possible, and no later than a week from now, you will get the PR for Hacktoberfest. If not, I have to award it to the other user. If you feel you can't deliver on this after all, please let me know so I can award it to the other user as soon as possible.

Thank you again for your interest. I am looking forward to seeing your solution. :)

**Comment by Reza9472** [comment]
Thank you for the message. I will definitely try to submit mine within this week. If I ran into problems, I'll let you know so you can assign it to someone else.
Thank you

**Comment by Reza9472** [comment]
Please check my PR and let me know if it needs anything
